<a href="https://colab.research.google.com/github/BhushanD01/Machine-Learning/blob/master/Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Numpy Library**

In [ ]:
import numpy as np

**Matrix Addition**

Note: Two Matrices can only be added if they have the same shape.

In [ ]:
a = np.array([[2,3],[4,5]])

b = np.array([[6,7],[8,9]])

print(a+b)

[[ 8 10]
 [12 14]]


In [ ]:
# creating two matrices with random values

matrix_1 = np.random.randint(10, size=(3,3))

matrix_2 = np.random.randint(30, size=(3,3))



print(matrix_1)



[[6 0 7]
 [1 9 8]
 [3 6 3]]


In [ ]:
print(matrix_2)

[[23  6  5]
 [29 21 13]
 [13 10 22]]


In [ ]:
matrix_addition = np.add(matrix_1, matrix_2)

print(matrix_addition)

[[29  6 12]
 [30 30 21]
 [16 16 25]]


**Matrix Subtraction**

Note: Two Matrices can only be subtracted if they have the same shape.

In [ ]:
a = np.array([[6,7],[8,9]])

b = np.array([[1,2],[3,4]])

print(a-b)

[[5 5]
 [5 5]]


In [ ]:
matrix_3 = np.random.randint(10, size=(3,3))

matrix_4 = np.random.randint(30, size=(3,3))



print(matrix_3)

[[0 5 6]
 [3 7 0]
 [6 4 9]]


In [ ]:
print(matrix_4)

[[25 19 16]
 [14  4 14]
 [16  0 28]]


In [ ]:
matrix_subtraction = np.subtract(matrix_3, matrix_4)

print(matrix_subtraction)

[[-25 -14 -10]
 [-11   3 -14]
 [-10   4 -19]]


**Multiplying a matrix by a scalar**

In [ ]:
x = 5

y = np.random.randint(10, size=(3,3))

print(y)

[[6 8 2]
 [4 4 4]
 [5 6 3]]


In [ ]:
product = x * y

print(product)

[[30 40 10]
 [20 20 20]
 [25 30 15]]


**Multiplying two Matrices**

Note: The number of columns in the first matrix should be equal to the number of rows in the second matrix.

In [ ]:
matrix_5 = np.random.randint(10, size=(3,3))

matrix_6 = np.random.randint(30, size=(3,4))



print(matrix_5)

[[6 9 5]
 [0 2 6]
 [7 3 3]]


In [ ]:
print(matrix_6)

[[26  6  7 22]
 [19 16  0 20]
 [ 5 27  6 13]]


In [19]:
product = np.dot(matrix_5, matrix_6)

print(product)

[[352 315  72 377]
 [ 68 194  36 118]
 [254 171  67 253]]


**Element wise Matrix Multiplication**

In [21]:
matrix_7 = np.random.randint(10, size=(3,3))

matrix_8 = np.random.randint(10, size=(3,3))


print(matrix_7)

[[7 7 2]
 [5 6 9]
 [8 1 4]]


In [23]:
print(matrix_8)

[[3 9 6]
 [5 5 8]
 [0 6 6]]


In [25]:
# Both matrix should have same shape for np.multiply
product = np.multiply(matrix_7, matrix_8)

print(product)

[[21 63 12]
 [25 30 72]
 [ 0  6 24]]
